### PR TITLE
Add dei extension

### PR DESCRIPTION
**Pull request by mrshll1001**
This will add the dei extension into the registry and enable tooling to fetch it on the main branch

### CODE REVIEW

**Comment by mrshll1001** [comment]
@KDuerden, this is safe to be merged in when ready. Neelima has the instructions to hit merge, but i've set it up so that it needs an approving review if you could be so kind :-)

**Comment by michaelwood** [comment]
feedback from @KDuerden via odsc ticket 47221 :

> 1. It currently says ['Equality'](https://github.com/ThreeSixtyGiving/extensions-registry/pull/2/files#diff-f91f0f3f7aa3a01a151b396ae8414914ffadc4c891e9830d992cb8da7530b786R4) in the validation section but that is incorrect, it needs to say "Diversity, Equity , and Inclusion Extension (dei)"
> 2. There is a [link to the DEI extension section](https://github.com/ThreeSixtyGiving/extensions-registry/pull/2/files#diff-f91f0f3f7aa3a01a151b396ae8414914ffadc4c891e9830d992cb8da7530b786R5) in that text that needs a hash as the end remove - it should be https://standard.threesixtygiving.org/en/latest/extensions/dei/

**Comment by KDuerden** [comment]
> feedback from @KDuerden via odsc ticket 47221 :
> 
> > 1. It currently says ['Equality'](https://github.com/ThreeSixtyGiving/extensions-registry/pull/2/files#diff-f91f0f3f7aa3a01a151b396ae8414914ffadc4c891e9830d992cb8da7530b786R4) in the validation section but that is incorrect, it needs to say "Diversity, Equity , and Inclusion Extension (dei)"
> > 2. There is a [link to the DEI extension section](https://github.com/ThreeSixtyGiving/extensions-registry/pull/2/files#diff-f91f0f3f7aa3a01a151b396ae8414914ffadc4c891e9830d992cb8da7530b786R5) in that text that needs a hash as the end remove - it should be https://standard.threesixtygiving.org/en/latest/extensions/dei/

Thanks @michaelwood - this PR needs to be updated with those comments. @neelima-j are you ok to action this and then I'll approve. This is outside the 360Giving Data Standard governance process so I can do that as soon as this is amended. Thank you.

**Comment by neelima-j** [comment]
@KDuerden  Thanks for the tag! Changes made and ready for review

**Review by KDuerden — APPROVED** [review]
Thanks for making this change, I'm happy to approve this.

**Pull request merged**
